### ISSUE TITLE
Cannot open menus from OSX menu bar (Oracle 1.8 VM)

### ISSUE THREAD

**Issue by robertoschwald** [tbrandt77/janrufmonitor#15]
With Oracle 1.8.0_111 VM, the menu windows (info, settings) do not open from the main menu bar option. However, they can be opened from the menu bar application icon.
See screenshots:

![master_4827d6_menubar_does_not_open_windows](https://cloud.githubusercontent.com/assets/1519879/21519859/8de5ab22-ccf0-11e6-9a9e-d2a0237e2505.png)

![master_4827d6_menubar_icon_does_open](https://cloud.githubusercontent.com/assets/1519879/21519861/9042003c-ccf0-11e6-9aad-b3ba64f86fe2.png)

**Comment by tbrandt77** [comment]
I am using SWT on Cocoa and have not yet found a hook to get the preferences opened via OS X menu. Any idea how this can be accomplished?

**Comment by robertoschwald** [comment]
Maybe this one? http://eclipsesource.com/blogs/2012/07/19/configuring-the-os-x-application-menu-for-swt-apps/

**Comment by robertoschwald** [comment]
Fix for this issue would be, to avoid having the application Dock item displayed and use it as a TrayIcon application when using Oracle JVM (like it is when using Apple Java6).

For this, I added the following key to the Info.plist file:

<key>LSUIElement</key>
<string>1</string>

which gets rid of the Dock icon, and the standard OSX Application Menu, so you use only the tray icon to control the app. This BTW would also fix #16 

However, we need to find a way to configure LSUIElement in the appbundler Ant task...

**Comment by tbrandt77** [comment]
Found this appbundler fork which seems to make it: https://github.com/ome/appbundler

**Comment by robertoschwald** [comment]
This appbundler fork has "hideDockItem" option, which sets LSUIElement in the Info.plist file:

https://bitbucket.org/infinitekind/appbundler

See https://bitbucket.org/infinitekind/appbundler/src/408678f4b1df0607a8bd4a183932195c23c0f714/appbundler/doc/appbundler.html?at=default&fileviewer=file-view-default#appbundler.html-79

Please await PR.

**Comment by robertoschwald** [comment]
Thats the same. I tested it, it works! 

PR follows.

**Comment by tbrandt77** [comment]
PR not required, I have it already adopted

**Comment by robertoschwald** [comment]
too late ;-)

**Comment by tbrandt77** [comment]
solved with commit https://github.com/tbrandt77/janrufmonitor/commit/0fb228c3fe54bab322476d6a4bab198650ecc464
