### ISSUE TITLE
JVM Crash on Module-Install restart (OSX, Oracle JVM 1.8)

### ISSUE THREAD

**Issue by robertoschwald** [tbrandt77/janrufmonitor#16]
On any module install/uninstall restart of the application, the JVM crashes.

Application Log see [jam-0.txt](https://github.com/tbrandt77/janrufmonitor/files/675422/jam-0.txt) excerpt.

Crash log (See especially "Thread 6"):

Process:               JavaAppLauncher [23572]
Path:                  /Applications/jAnrufmonitor - AVM FRITZ!Box Edition.app/Contents/MacOS/JavaAppLauncher
Identifier:            de.janrufmonitor.core
Version:               5.0.69 (1)
Code Type:             X86-64 (Native)
Responsible:           JavaAppLauncher [23572]

Date/Time:             2016-12-28 11:32:55.333 +0100
OS Version:            Mac OS X 10.12.2 (16C67)
Report Version:        12

Time Awake Since Boot: 380000 seconds
Time Since Wake:       7300 seconds

System Integrity Protection: enabled

Crashed Thread:        6

Exception Type:        EXC_BAD_ACCESS (SIGABRT)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000078
Exception Note:        EXC_CORPSE_NOTIFY

VM Regions Near 0x78:
--> 
    __TEXT                 00000001002f3000-00000001002f6000 [   12K] r-x/rwx SM=COW  /Applications/jAnrufmonitor - AVM FRITZ!Box Edition.app/Contents/MacOS/JavaAppLauncher

Application Specific Information:
abort() called

Thread 0:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fffbd23cc86 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fffbd32696a _pthread_cond_wait + 712
2   libjvm.dylib                  	0x000000010084d8a6 os::PlatformEvent::park() + 192
3   libjvm.dylib                  	0x000000010082a9b2 ParkCommon(ParkEvent*, long) + 42
4   libjvm.dylib                  	0x000000010082b288 Monitor::IWait(Thread*, long) + 168
5   libjvm.dylib                  	0x000000010082b458 Monitor::wait(bool, long, bool) + 222
6   libjvm.dylib                  	0x000000010097e6b1 VMThread::execute(VM_Operation*) + 269
7   libjvm.dylib                  	0x00000001006b377a vm_exit(int) + 140
8   libjvm.dylib                  	0x0000000100716d64 JVM_Halt + 73
9   ???                           	0x00000001096f2c84 0 + 4453248132
10  ???                           	0x00000001096db33d 0 + 4453151549
11  ???                           	0x00000001096db33d 0 + 4453151549
12  ???                           	0x00000001096db33d 0 + 4453151549
13  ???                           	0x00000001096db33d 0 + 4453151549
14  ???                           	0x00000001096db33d 0 + 4453151549
15  ???                           	0x00000001096db33d 0 + 4453151549
16  ???                           	0x00000001096db382 0 + 4453151618
17  ???                           	0x000000010a60b55c 0 + 4469077340

Thread 1:
0   libsystem_kernel.dylib        	0x00007fffbd23cc86 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fffbd32696a _pthread_cond_wait + 712
2   com.apple.Foundation          	0x00007fffa95dadcb -[NSCondition wait] + 240
3   com.apple.Foundation          	0x00007fffa95d9e88 -[NSObject(NSThreadPerformAdditions) performSelector:onThread:withObject:waitUntilDone:modes:] + 904
4   com.apple.Foundation          	0x00007fffa95d9a82 -[NSObject(NSThreadPerformAdditions) performSelectorOnMainThread:withObject:waitUntilDone:] + 131
5   libjli.dylib                  	0x0000000100372c4f JVMInit + 251
6   libjli.dylib                  	0x0000000100370169 JLI_Launch + 4837
7   de.janrufmonitor.core         	0x00000001002f5990 launch + 5696
8   de.janrufmonitor.core         	0x00000001002f4136 main + 102
9   libjli.dylib                  	0x000000010037358f apple_main + 92
10  libsystem_pthread.dylib       	0x00007fffbd325aab _pthread_body + 180
11  libsystem_pthread.dylib       	0x00007fffbd3259f7 _pthread_start + 286
12  libsystem_pthread.dylib       	0x00007fffbd3251fd thread_start + 13

Thread 2:
0   libsystem_kernel.dylib        	0x00007fffbd23cc86 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fffbd32696a _pthread_cond_wait + 712
2   libjvm.dylib                  	0x000000010084d8a6 os::PlatformEvent::park() + 192
3   libjvm.dylib                  	0x000000010082a9b2 ParkCommon(ParkEvent*, long) + 42
4   libjvm.dylib                  	0x000000010082b288 Monitor::IWait(Thread*, long) + 168
5   libjvm.dylib                  	0x000000010082b4f1 Monitor::wait(bool, long, bool) + 375
6   libjvm.dylib                  	0x000000010063ca7a GCTaskManager::get_task(unsigned int) + 56
7   libjvm.dylib                  	0x000000010063db47 GCTaskThread::run() + 349
8   libjvm.dylib                  	0x0000000100851b0a java_start(Thread*) + 246
9   libsystem_pthread.dylib       	0x00007fffbd325aab _pthread_body + 180
10  libsystem_pthread.dylib       	0x00007fffbd3259f7 _pthread_start + 286
11  libsystem_pthread.dylib       	0x00007fffbd3251fd thread_start + 13

Thread 3:
0   libsystem_kernel.dylib        	0x00007fffbd23cc86 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fffbd32696a _pthread_cond_wait + 712
2   libjvm.dylib                  	0x000000010084d8a6 os::PlatformEvent::park() + 192
3   libjvm.dylib                  	0x000000010082a9b2 ParkCommon(ParkEvent*, long) + 42
4   libjvm.dylib                  	0x000000010082b288 Monitor::IWait(Thread*, long) + 168
5   libjvm.dylib                  	0x000000010082b4f1 Monitor::wait(bool, long, bool) + 375
6   libjvm.dylib                  	0x000000010063ca7a GCTaskManager::get_task(unsigned int) + 56
7   libjvm.dylib                  	0x000000010063db47 GCTaskThread::run() + 349
8   libjvm.dylib                  	0x0000000100851b0a java_start(Thread*) + 246
9   libsystem_pthread.dylib       	0x00007fffbd325aab _pthread_body + 180
10  libsystem_pthread.dylib       	0x00007fffbd3259f7 _pthread_start + 286
11  libsystem_pthread.dylib       	0x00007fffbd3251fd thread_start + 13

Thread 4:
0   libsystem_kernel.dylib        	0x00007fffbd23cc86 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fffbd32696a _pthread_cond_wait + 712
2   libjvm.dylib                  	0x000000010084d8a6 os::PlatformEvent::park() + 192
3   libjvm.dylib                  	0x000000010082a9b2 ParkCommon(ParkEvent*, long) + 42
4   libjvm.dylib                  	0x000000010082b288 Monitor::IWait(Thread*, long) + 168
5   libjvm.dylib                  	0x000000010082b4f1 Monitor::wait(bool, long, bool) + 375
6   libjvm.dylib                  	0x000000010063ca7a GCTaskManager::get_task(unsigned int) + 56
7   libjvm.dylib                  	0x000000010063db47 GCTaskThread::run() + 349
8   libjvm.dylib                  	0x0000000100851b0a java_start(Thread*) + 246
9   libsystem_pthread.dylib       	0x00007fffbd325aab _pthread_body + 180
10  libsystem_pthread.dylib       	0x00007fffbd3259f7 _pthread_start + 286
11  libsystem_pthread.dylib       	0x00007fffbd3251fd thread_start + 13

Thread 5:
0   libsystem_kernel.dylib        	0x00007fffbd23cc86 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fffbd32696a _pthread_cond_wait + 712
2   libjvm.dylib                  	0x000000010084d8a6 os::PlatformEvent::park() + 192
3   libjvm.dylib                  	0x000000010082a9b2 ParkCommon(ParkEvent*, long) + 42
4   libjvm.dylib                  	0x000000010082b288 Monitor::IWait(Thread*, long) + 168
5   libjvm.dylib                  	0x000000010082b4f1 Monitor::wait(bool, long, bool) + 375
6   libjvm.dylib                  	0x000000010063ca7a GCTaskManager::get_task(unsigned int) + 56
7   libjvm.dylib                  	0x000000010063db47 GCTaskThread::run() + 349
8   libjvm.dylib                  	0x0000000100851b0a java_start(Thread*) + 246
9   libsystem_pthread.dylib       	0x00007fffbd325aab _pthread_body + 180
10  libsystem_pthread.dylib       	0x00007fffbd3259f7 _pthread_start + 286
11  libsystem_pthread.dylib       	0x00007fffbd3251fd thread_start + 13

Thread 6 Crashed:
0   libsystem_kernel.dylib        	0x00007fffbd23cdd6 __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fffbd328787 pthread_kill + 90
2   libsystem_c.dylib             	0x00007fffbd1a2420 abort + 129
3   libjvm.dylib                  	0x00000001008512bb os::abort(bool) + 25
4   libjvm.dylib                  	0x00000001009780e6 VMError::report_and_die() + 2304
5   libjvm.dylib                  	0x0000000100852ee6 JVM_handle_bsd_signal + 1131
6   libjvm.dylib                  	0x000000010084f14b signalHandler(int, __siginfo*, void*) + 47
7   libsystem_platform.dylib      	0x00007fffbd31bbba _sigtramp + 26
8   libjvm.dylib                  	0x0000000100613770 frame::sender_for_interpreter_frame(RegisterMap*) const + 120
9   libswt-cocoa-4527.jnilib      	0x00000001056af25e fn0_2 + 39
10  com.apple.AddressBook.framework	0x00007fffa544bf6e ab_dispatch_wait_for_operation_queue + 54
11  com.apple.AddressBook.framework	0x00007fffa544bebd _ABExitFunction + 99
12  libsystem_c.dylib             	0x00007fffbd1a317f __cxa_finalize_ranges + 339
13  libsystem_c.dylib             	0x00007fffbd1a34b2 exit + 55
14  libjvm.dylib                  	0x00000001006b36ee vm_direct_exit(int) + 28
15  libjvm.dylib                  	0x000000010097f771 VM_Operation::evaluate() + 79
16  libjvm.dylib                  	0x000000010097dddd VMThread::evaluate_operation(VM_Operation*) + 223
17  libjvm.dylib                  	0x000000010097e22a VMThread::loop() + 808
18  libjvm.dylib                  	0x000000010097db49 VMThread::run() + 121
19  libjvm.dylib                  	0x0000000100851b0a java_start(Thread*) + 246
20  libsystem_pthread.dylib       	0x00007fffbd325aab _pthread_body + 180
21  libsystem_pthread.dylib       	0x00007fffbd3259f7 _pthread_start + 286
22  libsystem_pthread.dylib       	0x00007fffbd3251fd thread_start + 13

**Comment by tbrandt77** [comment]
solved with commit https://github.com/tbrandt77/janrufmonitor/commit/0fb228c3fe54bab322476d6a4bab198650ecc464
