### ISSUE TITLE
Change default preferences and log paths on OSX

### ISSUE THREAD

**Issue by robertoschwald** [tbrandt77/janrufmonitor#17]
1. On OSX, all application preferences should be stored by default in
    
    $HOME/Library/Application Support/<application_name> instead of the Documents folder

2. The log-file is currently stored in the application paths Java/logs dir. The Application dir is not always writeable by users. User Logs on OSX should be stored in 

    $HOME/Library/Logs/

directory. Advantage of using this dir is, that the standard "Console.app" on OSX shows these logs automatically.

**Comment by tbrandt77** [comment]
Log location changed on the commit https://github.com/tbrandt77/janrufmonitor/commit/36c6a62d8dbe4bcb7f7fd4b178b955246d256fab

**Comment by tbrandt77** [comment]
ad 1) what do you expect to be a preference? Configuration data, module data, archives, history files?

**Comment by robertoschwald** [comment]
1) All dynamic data, like DBs etc., which are currently stored by default in Documents/jAnrufmonitor

**Comment by tbrandt77** [comment]
Documents/jAnrufmonitor stores user data and no program data currently. I would like to leave this as it is, since otherwise you won't find user data like the journal and contacts in the system. Settings, preferences and program data like the country DB make sense to move to $HOME/Library/Application Support/<application_name>

**Comment by robertoschwald** [comment]
For me, the sqlite3 db is a candidate for Application Settings, not for Documents.

**Comment by tbrandt77** [comment]
It's a hsqldb file which contains the journal and the contact data of the logged in user. So I think this data need to be in the Documents folder also for being ready to be considered on user data backups etc.

**Comment by robertoschwald** [comment]
Can you explain what you mean by "ready to be considered on user data backup"? On Time-Machine backups, the Application Preferences folder is also backed up.

**Comment by tbrandt77** [comment]
Time Machine for sure, but not on iCloud afaik

**Comment by robertoschwald** [comment]
I see. Good point.

**Comment by robertoschwald** [comment]
BTW: Tested the new logpath setting, but it does not work here. The logging.properties holds the %logpath% placeholder, but it seems it is not populated.

When I manually replace %logpath% in logging.properties with an actual path, it works.

**Comment by tbrandt77** [comment]
Issue with logpath is solved with commit https://github.com/tbrandt77/janrufmonitor/commit/4508b61c91619337b9ab937090cd4018efc5c5be

**Comment by robertoschwald** [comment]
Still got an issue with the logpath. Now it logs to "$HOME/Library:Logs:jAnrufmonitor" (with the colons), but it should log to "$HOME/Library/Logs/jAnrufmonitor/".

Is there an issue with the separator?

**Comment by tbrandt77** [comment]
I use File.separator as path divider. This works for me on any platform.

**Comment by robertoschwald** [comment]
Thats what I saw in the PathResolver, but here, it does not create in Library/Logs, but in this strange dir "Library:Logs...". 

Normally, it should be enough to perform an "ant clean" before rebuild, right? Is there some cache involved I need to clear before building the project?

**Comment by tbrandt77** [comment]
No, there are no caches afaik

**Comment by tbrandt77** [comment]
You should check why File.separator is returning : instead of /

**Comment by robertoschwald** [comment]
Was a local error on the iMac. I tried on anotherone and it worked. Re-Cloned the repo, now it works.
