### ISSUE TITLE
Windows are not in foreground when opened

### ISSUE THREAD

**Issue by robertoschwald** [tbrandt77/janrufmonitor#20]
On OSX 10.12, the windows (Preferences, initial Config wizard, etc) are opened in the background all the time.

See also user report: https://www.janrufmonitor.de/foren/topic/fenster-nicht-im-vordergrund/ 

Successfully tested a fix in ConfigurationCommand to force the configuration shell to foreground by setting shell.forceActive(), but I'm not sure about the implications to other platforms. 

```java
			Shell shell = new Shell(display);
			PreferenceDialog dlg = new PreferenceDialog(shell, mgr);
			dlg.setPreferenceStore(new PreferenceConfigManagerStore());
			shell.forceActive();
			dlg.open();
```

**Comment by robertoschwald** [comment]
All my tries so far (see commits) do not work reliable. When another application is active in the foreground, Administration > Settings window will be opened in the background. Out of ideas.

**Comment by tbrandt77** [comment]
Did you try forceFocus() together with forceActive()?

**Comment by robertoschwald** [comment]
Yes. Doesn't help.

**Comment by robertoschwald** [comment]
Probably. I dig further.

**Comment by robertoschwald** [comment]
fixed with the merged pull request.
