### ISSUE TITLE
Native?

### ISSUE THREAD

**Issue by hurzl** [tbrandt77/janrufmonitor#4]
Werden da native libs verwendet oder warum hat man nur die Auswahl zwischen 3 Systemen?

**Comment by tbrandt77** [comment]
Was meinst du mit "Auswahl zwischen 3 Systemen"?

**Comment by hurzl** [comment]
Na Windows, OSX und Linux

**Comment by tbrandt77** [comment]
Ja, zu diesen Betriebsystemen gibt es native libs.
