### ISSUE TITLE
Support for universalJavaApplicationStub on OSX

### ISSUE THREAD

**Issue by robertoschwald** [tbrandt77/janrufmonitor#9]
Currently, the old, outdated Apple JavaApplicationStub with plist file is used, which uses the insecure, old Java6 of former OSX versions.

Better approach is to use https://github.com/tofi86/universalJavaApplicationStub, which runs with Oracle Java 8.

PR follows.

**Comment by tbrandt77** [comment]
Support for Oracle Appbundler 2.0 is planned for next release. It is already committed to GitHub (https://github.com/tbrandt77/janrufmonitor/commit/2d3e04c6dd9649a43096795b1168cd2391b8f5f3) some weeks ago. Will make it to the release for Feb., 2017

**Comment by robertoschwald** [comment]
Just saw it. It might be a good idea to make the following changes to the current code base:

- add "build_modules" as dependency to bundle_macos64_oracle target (so the required modules are build automatically, otherwise you get an error and need to either build build_modules or only the required modules, manually )
- remove "runtime" param from appbundler (due to licensing issues)

**Comment by robertoschwald** [comment]
Also, the dmg creation does not work here, unless I disable "cd $BASE" and replace "/Users/brandtt" with "$HOME".
My OSX is 10.12.2

**Comment by robertoschwald** [comment]
I provide a PR in a few minutes.
